
import { Order } from './types';

// Sample order data
export const sampleOrders: Order[] = [
  {
    id: 'ORD-0001',
    orderDate: '2023-03-12',
    customer: 'John Smith',
    status: 'collected',
    studio: 'Downtown Studio',
    driver: 'Michael Davis',
    total: 45.99,
    deliveryDate: '2023-03-14',
  },
  {
    id: 'ORD-0002',
    orderDate: '2023-03-13',
    customer: 'Emma Johnson',
    status: 'in-progress',
    studio: 'Westside Studio',
    driver: 'Sarah Wilson',
    total: 32.50,
    deliveryDate: null,
  },
  {
    id: 'ORD-0003',
    orderDate: '2023-03-13',
    customer: 'James Brown',
    status: 'ready-for-collect',
    studio: 'Eastside Studio',
    driver: 'Robert Miller',
    total: 78.25,
    deliveryDate: null,
  },
  {
    id: 'ORD-0004',
    orderDate: '2023-03-14',
    customer: 'Olivia Davis',
    status: 'new',
    studio: 'Downtown Studio',
    driver: 'Unassigned',
    total: 54.75,
    deliveryDate: null,
  },
  {
    id: 'ORD-0005',
    orderDate: '2023-03-11',
    customer: 'William Taylor',
    status: 'cancelled',
    studio: 'Northside Studio',
    driver: 'Cancelled',
    total: 0,
    deliveryDate: null,
  },
  {
    id: 'ORD-0006',
    orderDate: '2023-03-15',
    customer: 'Sophia Martinez',
    status: 'received',
    studio: 'Downtown Studio',
    driver: 'Pending Assignment',
    total: 29.99,
    deliveryDate: null,
  },
  {
    id: 'ORD-0007',
    orderDate: '2023-03-10',
    customer: 'Daniel Johnson',
    status: 'delivered',
    studio: 'Southside Studio',
    driver: 'Thomas Rodriguez',
    total: 63.45,
    deliveryDate: '2023-03-12',
  },
  {
    id: 'ORD-0008',
    orderDate: '2023-03-09',
    customer: 'Olivia Wilson',
    status: 'delivered',
    studio: 'Downtown Studio',
    driver: 'Michael Davis',
    total: 42.30,
    deliveryDate: '2023-03-11',
  }
];
